packages/adyen-retail-react-app/overrides/app/routes.jsx
packages/adyen-salesforce-pwa/lib/api/controllers/payments.js
packages/adyen-salesforce-pwa/lib/components/adyenCheckout.jsx
packages/adyen-salesforce-pwa/lib/components/paymentMethodsConfiguration.js
packages/adyen-salesforce-pwa/lib/context/adyen-checkout-context.jsx
packages/adyen-salesforce-pwa/lib/pages/checkout/index.jsx

- Provide a config object with customizations
- Enable merchants to customize our checkout component
- Payments
- Modify payment methods style
**Fixed issue**:  SFI-507

Customization config for AdyenCheckout component

---

packages/adyen-salesforce-pwa/README.md
packages/adyen-salesforce-pwa/package-lock.json
packages/adyen-salesforce-pwa/package.json

- Upgrade to latest api library
- Use latest Checkout API
- Card payments
- PayPal
- Amazon
**Fixed issue**:  SFI-615

feat: upgrade api library to v16

---

README.md

Olga adyen patch 1

---

packages/adyen-salesforce-pwa/README.md
packages/adyen-salesforce-pwa/jest.config.js
packages/adyen-salesforce-pwa/lib/components/adyenCheckout.jsx
packages/adyen-salesforce-pwa/lib/components/tests/adyenCheckout.test.js
packages/adyen-salesforce-pwa/lib/context/tests/adyen-checkout-context.test.js
packages/adyen-salesforce-pwa/package-lock.json
packages/adyen-salesforce-pwa/package.json

- increase unit test coverage
- higher code quality
- Payments
**Fixed issue**:  SFI-552

unit tests adyen checkout

---

packages/adyen-salesforce-pwa/lib/pages/checkout/partials/payment.jsx

- submit billing address
- submit billing address when BillingSameAsShipping is false
- 3DS and no 3DS payment flow
**Fixed issue**:  #SFI-602

SFI-602 submit billing address when BillingSameAsShipping is false

---

packages/adyen-retail-react-app/package-lock.json
packages/adyen-retail-react-app/package.json
packages/adyen-salesforce-pwa/lib/utils/constants.mjs
packages/adyen-salesforce-pwa/package-lock.json
packages/adyen-salesforce-pwa/package.json

- Prepare for release
**Fixed issue**:  SFI-582

Bump version to 1.0.0

---

packages/adyen-retail-react-app/overrides/app/ssr.js

- Modify the ssr headers
- Render google pay button
- Google Pay

fix: add google pay script to the headers

---

packages/adyen-retail-react-app/overrides/app/pages/cart/index.jsx
packages/adyen-retail-react-app/overrides/app/pages/cart/partials/cart-cta.jsx
packages/adyen-retail-react-app/overrides/app/routes.jsx
packages/adyen-salesforce-pwa/lib/components/applePayExpress.jsx
packages/adyen-salesforce-pwa/lib/context/adyen-express-checkout-context.jsx
packages/adyen-salesforce-pwa/lib/index.js
packages/adyen-salesforce-pwa/lib/style/adyenCheckout.css

- Show apple buttons on cart page
- Making an express payment
- Render buttons
**Fixed issue**:  SFI-569

Render ApplePay express button

---

packages/adyen-retail-react-app/overrides/app/pages/cart/index.jsx
packages/adyen-retail-react-app/overrides/app/pages/cart/partials/cart-cta.jsx
packages/adyen-salesforce-pwa/lib/api/controllers/payments.js
packages/adyen-salesforce-pwa/lib/api/controllers/shipping-address.js
packages/adyen-salesforce-pwa/lib/api/controllers/shipping-methods.js
packages/adyen-salesforce-pwa/lib/api/controllers/tests/shipping-address.test.js
packages/adyen-salesforce-pwa/lib/api/controllers/tests/shipping-methods.test.js
packages/adyen-salesforce-pwa/lib/api/index.js
packages/adyen-salesforce-pwa/lib/api/routes/index.js
packages/adyen-salesforce-pwa/lib/api/routes/tests/index.test.js
packages/adyen-salesforce-pwa/lib/components/applePayExpress.jsx
packages/adyen-salesforce-pwa/lib/components/tests/applePayExpress.test.js
packages/adyen-salesforce-pwa/lib/contexts/adyen-express-checkout-context.jsx
packages/adyen-salesforce-pwa/lib/contexts/tests/adyen-express-checkout-context.test.js
packages/adyen-salesforce-pwa/lib/services/shipping-address.js
packages/adyen-salesforce-pwa/lib/services/shipping-methods.js
packages/adyen-salesforce-pwa/lib/services/tests/shipping-address.test.js
packages/adyen-salesforce-pwa/lib/services/tests/shipping-methods.test.js
packages/adyen-salesforce-pwa/package-lock.json
packages/adyen-salesforce-pwa/package.json

- Provide the shipping details to payments request
- Provide the correct address
- Apple Pay Express
**Fixed issue**:  SFI-634

Shipping details

---

packages/adyen-retail-react-app/package-lock.json
packages/adyen-retail-react-app/package.json
packages/adyen-salesforce-pwa/README.md
packages/adyen-salesforce-pwa/lib/api/controllers/tests/payment-methods.test.js
packages/adyen-salesforce-pwa/lib/utils/constants.mjs
packages/adyen-salesforce-pwa/package-lock.json
packages/adyen-salesforce-pwa/package.json

- Increment version
- Prepare for release

Bump version

---

packages/adyen-retail-react-app/overrides/app/components/_app/index.jsx
packages/adyen-retail-react-app/overrides/app/components/header/index.jsx
packages/adyen-retail-react-app/overrides/app/pages/cart/partials/cart-cta.jsx
packages/adyen-retail-react-app/overrides/app/pages/checkout/confirmation.jsx
packages/adyen-retail-react-app/overrides/app/pages/checkout/index.jsx
packages/adyen-retail-react-app/package.json
packages/adyen-salesforce-pwa/lib/api/controllers/payments.js
packages/adyen-salesforce-pwa/lib/components/applePayExpress.jsx
packages/adyen-salesforce-pwa/lib/components/card/config.js
packages/adyen-salesforce-pwa/lib/components/tests/cardConfig.test.js
packages/adyen-salesforce-pwa/lib/contexts/adyen-checkout-context.jsx
packages/adyen-salesforce-pwa/lib/contexts/adyen-express-checkout-context.jsx
packages/adyen-salesforce-pwa/lib/contexts/tests/adyen-checkout-context.test.js
packages/adyen-salesforce-pwa/lib/contexts/tests/adyen-express-checkout-context.test.js
packages/adyen-salesforce-pwa/package-lock.json
packages/adyen-salesforce-pwa/package.json
packages/adyen-salesforce-pwa/webpack.config.js

- Adapt the components and apis to be used in v2 of pwa-kit
- Enable merchants using v2 to use our npm package
- 3ds2 payments
- APM payments
- Apple Pay Express
**Fixed issue**:  SFI-709

Compatibility with PWA v2.x.x

---

packages/adyen-retail-react-app/config/sites.js
packages/adyen-retail-react-app/overrides/app/components/_app/index.jsx
packages/adyen-retail-react-app/overrides/app/components/header/index.jsx
packages/adyen-retail-react-app/overrides/app/pages/checkout/redirect/index.jsx
packages/adyen-retail-react-app/overrides/app/static/translations/compiled/ja-JP.json
packages/adyen-retail-react-app/overrides/app/static/translations/compiled/pt-BR.json
packages/adyen-retail-react-app/package.json
packages/adyen-salesforce-pwa/lib/api/controllers/payments.js
packages/adyen-salesforce-pwa/lib/components/helpers/baseConfig.js
packages/adyen-salesforce-pwa/lib/components/tests/baseConfig.test.js
packages/adyen-salesforce-pwa/lib/contexts/adyen-checkout-context.jsx
packages/adyen-salesforce-pwa/lib/contexts/tests/adyen-checkout-context.test.js
packages/adyen-salesforce-pwa/package-lock.json
packages/adyen-salesforce-pwa/package.json
packages/e2e-tests/data/localeData.js
packages/e2e-tests/data/shopperData.js
packages/e2e-tests/helpers/PaymentHelper.js
packages/e2e-tests/helpers/ScenarioHelper.js
packages/e2e-tests/tests/ideal.spec.js

- New iDEAL flow 
- Adapting the new iDEAL requirements
- iDEAL payment methods
**Fixed issue**:  SFI-772

New iDEAL flow

---

packages/adyen-retail-react-app/overrides/app/pages/cart/partials/cart-cta.jsx

- Adapt apple pay express to the new v2.7 compatibility
- Make the express payments work for v2.7
- Apple Pay Express
**Fixed issue**:  SFI-799

Make apple pay express compatible with the new package

---

README.md
packages/adyen-retail-react-app/overrides/app/ssr.js
packages/adyen-retail-react-app/package-lock.json
packages/adyen-retail-react-app/package.json
packages/adyen-salesforce-pwa/lib/api/routes/index.js
packages/adyen-salesforce-pwa/lib/api/routes/tests/index.test.js
packages/adyen-salesforce-pwa/package-lock.json
packages/adyen-salesforce-pwa/package.json
packages/e2e-tests/helpers/ScenarioHelper.js

Properly parse the response inside our package
Merchants would benefit from this because Salesforce removed the body-parser dependency from their retail app
- Payments
**Fixed issue**:  SFI-822

Include body-parser in the npm package

---

packages/adyen-salesforce-pwa/lib/api/controllers/payments.js
packages/adyen-salesforce-pwa/lib/api/routes/index.js

Providing the required fields for Visa.
It passes the shopperIp in the payments request.
- Card payments
- Redirect payments
**Fixed issue**:  SFI-865

Compliance with the new Visa Secure Authentication requirements

---

packages/adyen-salesforce-pwa/lib/api/controllers/payments.js
packages/adyen-salesforce-pwa/lib/api/controllers/tests/payments.test.js
packages/adyen-salesforce-pwa/lib/api/routes/tests/index.test.js
packages/adyen-salesforce-pwa/lib/utils/getCardType.mjs
packages/adyen-salesforce-pwa/package-lock.json

Being able to use CREDIT_CARD as a payment method
Properly sync the payment method in OMS
- Card payments
- Paypal
- Klarna
- iDEAL
- Other APMs
**Fixed issue**:  SFI-870

Differentiate card payments from alternative payments

---

packages/adyen-retail-react-app/translations/fr-FR.json
packages/adyen-salesforce-pwa/webpack.config.js
packages/e2e-tests/data/localeData.js
packages/e2e-tests/helpers/ScenarioHelper.js

Easier debugging
Being able to see the source files in the debugger tab of the browser
- Code debugging
**Fixed issue**:  SFI-712

feat: generate source map for the builtin files

---

packages/adyen-retail-react-app/package-lock.json
packages/adyen-retail-react-app/package.json
packages/adyen-salesforce-pwa/package-lock.json
packages/adyen-salesforce-pwa/package.json

Provide more stable application
Get the latest upgrades
- Payments using our package
**Fixed issue**:  SFI-891

Dependencies upgrade

---

packages/adyen-salesforce-pwa/lib/api/controllers/payments.js
packages/adyen-salesforce-pwa/lib/api/controllers/tests/payments/createPaymentsRequestObject.test.js
packages/adyen-salesforce-pwa/lib/api/controllers/tests/payments/payments.test.js

- Send shopperInteraction for guest shoppers
- Send shopperInteraction for guest shoppers
- card payment flow
**Fixed issue**:  #SFI-1167

[SFI-1167] Send shopperInteraction for guest shoppers

---

packages/adyen-salesforce-pwa/lib/api/controllers/payments.js
packages/adyen-salesforce-pwa/lib/api/controllers/tests/payments/createPaymentsRequestObject.test.js

- - remove tax category from line items
-  remove tax category from line items
Klarna payment flow
**Fixed issue**:  #SFI-1280

[SFI-1280] remove tax category from line items

---

packages/adyen-salesforce-pwa/lib/components/adyenCheckout.jsx

- paypal button re-rendering
- paypal button re-rendering
- Paypal payment flow
**Fixed issue**: #SFI-1064

feat(SFI-1064): paypal button re-rendering
